export default {
  RSS: 'rss',
  BANDCAMP: 'bandcamp',
  SOUNDCLOUD: 'soundcloud',
  SONICSQUIRREL: 'sonicsquirrel',
  FACEBOOK: 'facebook',
  TWITTER: 'twitter',
  SITE: 'homepage',
  FMA: 'free_music_archive',
  ARCHIVE: 'internet_archive',
  INSTAGRAM: 'instagram',
  YOUTUBE: 'youtube',
  GOOGLE_PODCASTS: 'google-podcasts',
  APPLE_PODCASTS: 'apple-podcasts',
  RELEASES: 'release_rss',
};
